services:
    mdespeuilles.entity.meta:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Mdespeuilles\MetaBundle\Entity\Meta

    mdespeuilles.event.meta:
        class: Mdespeuilles\MetaBundle\EventListener\Meta
        arguments: [ '@request_stack' ]
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: setMeta }
